# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
  base_path: "build/ckeditor"
  js_path: "build/ckeditor/ckeditor.js"
  configs:
    my_config:
      skin: "moono"
      extraPlugins: "justify,colorbutton,smiley,specialchar,font"
      toolbar:
         - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', 'Table', '-', 'Styles', 'Format','FontSize', '-', 'TextColor', 'BGColor', '-', 'Smiley','SpecialChar'] }
      uiColor: "#8ed4cc"
      filebrowserBrowseRoute: elfinder
      filebrowserBrowseRouteParameters: []
    client_config:
      uiColor: "#8ed4cc"
      extraPlugins: "justify,colorbutton,smiley,specialchar"
      skin: "moono"
      toolbar: 
        - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Styles', 'Format', '-', 'TextColor', 'BGColor','-','Smiley','SpecialChar'] }
      


twig:
  form_themes:
    - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
