vich_uploader:
  db_driver: orm
  mappings:
    actuality_uploads:
      uri_prefix: "/uploads/vich/actuality"
      upload_destination: "%kernel.project_dir%/assets/uploads/vich/actuality"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    caroussel_uploads:
      uri_prefix: "/uploads/vich/carousel"
      upload_destination: "%kernel.project_dir%/assets/uploads/vich/carousel"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
