vich_uploader:
    db_driver: orm
    mappings:
        actuality_uploads:
            uri_prefix: "%app.path.actuality_images%"
            upload_destination: "%kernel.project_dir%/public%app.path.actuality_images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        caroussel_uploads:
            uri_prefix: "%app.path.carousel_images%"
            upload_destination: "%kernel.project_dir%/public%app.path.carousel_images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
